# Site settings
title: Edward Jivkov
email: edijivkov@gmail.com
author: Chrisanthropic

keywords: jekyll, jekyll theme, portfolio theme, artist theme
description: portfolio

# Only use this if you are serving your site via Github Pages
github:
  url: "https://github.com/edijivkov/"

header: images/logo.png

# Formspree contact Form
contact_form: "https://formspree.io/ctarwater@chrisanthropic.com"


# Exclude our ruby stuff
exclude: [.bundle, .vendor, .bin, starving-artist.gemspec, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, starving-artist-jekyll-theme-*.gem]


# Build settings
markdown: kramdown
kramdown:
  input: GFM

theme: starving-artist-jekyll-theme

# Plugins
gems:
  - jekyll-feed

feed:
  path: atom.xml

# Compress our Css
#sass:
#    style: :compressed

include: ['_pages']

permalink: /blog/:year/:title

collections:
  - galleries

#### SEO Stuff
# Google Analytics
google_universal_analytics:
google_universal_analytics_cookiedomain: auto
